name = "arachne"
type = "javascript"
account_id = "c8ddea43874d39279fccdbc60e6ac045"
workers_dev = true
zone_id = ""
route = ""
main = "./.cloudflare/worker.js"

[build]
command = "npm run build"

[site]
bucket = "./build"
entry-point = "./.cloudflare/"
