name = "arachne"
type = "javascript"
account_id = "c8ddea43874d39279fccdbc60e6ac045"
workers_dev = true

[build]
command = "npm run build"

# This is where the SvelteKit app's Cloudflare worker script will be generated
main = "./.cloudflare/worker.js"